### ISSUE TITLE
Support existing LCD

### ISSUE THREAD

**Issue by Lunagram** [cosmos/ethermint#161]
Hello, This is Daniel from Lunamint.

When I use 'emintcli rest-server', ethereum's method works fine.

ex) curl -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x938fa3d1273047251f67e767dee3596018e63aa8","data”:”0x81f22a92"}],"id":1}' -H "Content-Type: application/json" http://localhost:8545

However, I don't know how to run the Lcd for cosmos-sdk.
I have to use existing APIs like @GET / get_node_info, @POST / txs etc. 
(For my android application 'Lunagram')

Is there anything undocumented in this regard? Or can you tell me when to apply?

**Comment by austinabell** [comment]
Ah yes, this was something that was left on hold previously as it wasn't certain how these two servers would exist together. This was not addressed previously because no one yet has needed the Cosmos rest-server endpoints and was focused on the web3 rpc api but this should probably be done so thanks for bringing this up!

I have a TODO for where in the code the rest-server routes would be modified or added as a seperate command [here](https://github.com/ChainSafe/ethermint/blob/ce8a94a98ec1da3323639d596e3ee032293f4fe4/cmd/emintcli/main.go#L63). The options seem to be to attach the other Cosmos rest endpoints onto the same lcd server (currently the web3 api is attached to the cosmos lcd server at route `/`) or to have a seperate command for the web3 api and the Cosmos rest endpoints. 

I just played around with adding all Cosmos endpoints and it works with adding all routes on the same server (no conflicts as far as I can see as I don't think any Cosmos endpoint is at route `/` but I will look more in depth for this later). I have these changes on branch [austin/cosmosendpoints](https://github.com/ChainSafe/ethermint/tree/austin/cosmosendpoints). I tested the commands you mentioned in this issue and it seems to be working, but let me know if these changes are sufficient and I can open up a PR and get this merged in so others can use the Cosmos routes if needed.

**Comment by Lunagram** [comment]
Thanks for your hard work.

I have tested the functions below. It works fine except for one little issue.

It seems that all APIs of 'Cosmos LCD' do not support ethereum addresses. (like a 0xC42eb4B0095Bad59479fC10d147aD065863e8e68)

Please let me know if you support or do not support ethereum addresse. I will decide how to implement my app accordingly.

**Tested web3 APIs method**
 - eth_blockNumber
 - eth_getBalance
 - eth_call

**Tested Cosmos LCD APIs**
 - @GET /node_info
 - @GET /syncing
 - @GET /blocks/latest
 - @GET /blocks/{height}
 - @GET /validatorsets/latest
 - @GET /auth/accounts/{address} (**not supported ethereum address**)
 - @GET /bank/balances/{address} (**not supported ethereum address**)
 - @POST /txs

**Comment by austinabell** [comment]
no problem, it was quick since I already knew how to fix it.

Yeah the Cosmos API does not support Ethereum addresses, but this is nothing specific to Ethermint. It should be pretty easy to just convert the address to the Cosmos bech32 formatted address from the Ethereum address because the Ethereum address is just the hex formatted bytes of the Cosmos address.

Definitely willing to consider some sort of middleware or something inside Ethermint if you want to open up a PR to support this, but it's unlikely this will be investigated anytime soon otherwise.

**Comment by Lunagram** [comment]
Ok, I do not need it yet. Thank you :)
