### ISSUE TITLE
how can I send the transaction?

### ISSUE THREAD

**Issue by fnaticwang** [cosmos/ethermint#237]
Now that I have the node running according to the document, how can I send the transaction?  Do some accounts initialize balances? Or do I need to launch geth to create accounts and send transactions?

**Comment by ayeteng** [comment]
I found one video shows how to get transaction with web3.js.
https://youtu.be/Rws-QQ_qcfU
The repo is https://github.com/ChainSafe/ethermint-deploy
I am looking for a way to use web3.py.
Any suggestion?

**Comment by noot** [comment]
you can use web3.js or the geth console: `geth attach http://localhost:8545` see the [geth documentation](https://geth.ethereum.org/docs/getting-started) for more information on the geth javascript console. since ethermint uses the ethereum JSON-RPC, the geth console should work the same. please open another issue if you have more questions!
