### ISSUE TITLE
cannot request faucet funds to new accounts

### ISSUE THREAD

**Issue by noot** [cosmos/ethermint#522]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. `./init.sh`
2. `ethermintcli keys add testkey`
3. `ethermintcli tx faucet request 100photon --from testkey --chain-id 8 --fees 2aphoton`
4. error message: `failed to get from fields: The specified item could not be found in the keyring`
however, using the key that was loaded at genesis `mykey` works fine

__Expected behavior:__ [What you expected to happen]

able to send a tx to request funds

__Actual behavior:__ [What actually happened]

 error that key cannot be found

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by araskachoi** [comment]
So the issue is that the account only exists locally and cannot send any tx to until it has been initiated on the chain state. We can do this by either adding acct to genesis (not something we'll do for new accts) OR have the acct be a recipient of a tx.

https://github.com/cosmos/cosmos-sdk/issues/3322#issuecomment-522064190

The fix i attempted was instead of the faucet commands, I had sent a tx outright from the faucet account. However this might not work if I am requesting from an account on a node that does not own the faucet account. Will keep digging and see what can be done for that here.
